#!/usr/bin/env groovy

node ("docker&&linux"){
    stage('Checkout') {

        checkout scmGit(
                        branches: 
                        [[name: 'bootcamp']], 
                        extensions: [], 
                        userRemoteConfigs: [[url: 'https://github.com/hectorlopezv/cloudcamp-jenkins-lab']]
                        ) 
        
    }

    stage ('Build') {
        sh 'docker build -t "app/python-hello-world:1.0.0-beta.1" -f _scm_docker/Dockerfile _scm_docker/'
    }
}