#!/usr/bin/env groovy

node ('docker&&linux'){
    stage('Checkout') {

        checkout scmGit(
                        branches: 
                        [[name: 'bootcamp']], 
                        extensions: [], 
                        userRemoteConfigs: [[url: 'https://github.com/yaayala/cloudcamp-jenkins-lab']]
                        ) 
        
    }

    stage ('Build') {
        sh 'docker build -t "app/python-hello-world:1.0.0-beta.1" -f _scm_docker/Dockerfile _scm_docker/'
    }
    stage ('Push') {
        sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 851725481871.dkr.ecr.us-east-1.amazonaws.com'
        sh 'docker tag hello-world-python:latest 851725481871.dkr.ecr.us-east-1.amazonaws.com/hello-world-python:latest'
        sh 'docker push 851725481871.dkr.ecr.us-east-1.amazonaws.com/hello-world-python:latest'
        
    }
}